WARNING 2024-03-01 00:01:19,452 log 5892 5656 Unauthorized: /nexus/api/service/
WARNING 2024-03-01 00:01:19,453 basehttp 5892 5656 "GET /nexus/api/service/ HTTP/1.1" 401 183
WARNING 2024-03-01 00:03:40,989 log 5892 5656 Unauthorized: /nexus/api/service/1/details/
WARNING 2024-03-01 00:03:40,990 basehttp 5892 5656 "GET /nexus/api/service/1/details/ HTTP/1.1" 401 58
ERROR 2024-03-01 00:04:30,680 log 5892 5656 Internal Server Error: /nexus/api/service/1/details/
Traceback (most recent call last):
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\Desktop\Nexus_Capital\nexus_capital\api\views.py", line 256, in get
    service = get_object_or_404(Service, id=service_id, is_delete=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\shortcuts.py", line 86, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 635, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP USA\AppData\Roaming\Python\Python312\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'is_delete' into field. Choices are: description, id, is_deleted, payment, servicecatigories, title
ERROR 2024-03-01 00:04:30,694 basehttp 5892 5656 "GET /nexus/api/service/1/details/ HTTP/1.1" 500 147479
WARNING 2024-03-01 00:06:20,535 log 13428 13100 Not Found: /nexus/api/service/2/details/
WARNING 2024-03-01 00:06:20,536 basehttp 13428 13100 "GET /nexus/api/service/2/details/ HTTP/1.1" 404 23
WARNING 2024-03-01 00:35:18,233 log 6072 7392 Unauthorized: /nexus/api/service/
WARNING 2024-03-01 00:35:18,235 basehttp 6072 7392 "POST /nexus/api/service/ HTTP/1.1" 401 183
